name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build comparison site
        run: |
          set -euo pipefail

          # Fetch variant branches created via worktrees
          git fetch --no-tags origin alt-whisper-inline alt-whisper-modal || true

          mkdir -p site/variants/master site/variants/whisper-inline site/variants/whisper-modal

          # Baseline from current branch
          cp ve-boilerplate.html site/variants/master/index.html
          cp reading-styles.css site/variants/master/
          cp reading-script.js site/variants/master/

          # Whisper modal from branch
          if git rev-parse --verify --quiet origin/alt-whisper-modal >/dev/null; then
            git show origin/alt-whisper-modal:ve-boilerplate.html > site/variants/whisper-modal/index.html
            git show origin/alt-whisper-modal:reading-styles.css > site/variants/whisper-modal/reading-styles.css
            git show origin/alt-whisper-modal:reading-script.js > site/variants/whisper-modal/reading-script.js
          else
            echo "Missing branch origin/alt-whisper-modal; skipping modal variant"
          fi

          # Whisper inline from branch
          if git rev-parse --verify --quiet origin/alt-whisper-inline >/dev/null; then
            git show origin/alt-whisper-inline:ve-boilerplate.html > site/variants/whisper-inline/index.html
            git show origin/alt-whisper-inline:reading-styles.css > site/variants/whisper-inline/reading-styles.css
            git show origin/alt-whisper-inline:reading-script.js > site/variants/whisper-inline/reading-script.js
          else
            echo "Missing branch origin/alt-whisper-inline; skipping inline variant"
          fi

          # Static landing page
          cp pages-index.html site/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
