name: Deploy GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create HTML site
        run: |
          # Create homepage with article list
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Reader Discovery Research</title>
              <style>
                  body { 
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; 
                      max-width: 800px; 
                      margin: 0 auto; 
                      padding: 2rem; 
                      line-height: 1.6; 
                      background: #f6f6f6;
                  }
                  .header { 
                      text-align: center; 
                      margin-bottom: 3rem; 
                      background: #fff;
                      padding: 2rem;
                      border-radius: 8px;
                      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                  }
                  .article-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
                      gap: 1.5rem;
                      margin-bottom: 2rem;
                  }
                  .article-card {
                      background: #fff;
                      border: 1px solid #a2a9b1;
                      border-radius: 6px;
                      padding: 1.5rem;
                      transition: box-shadow 0.2s, transform 0.2s;
                      cursor: pointer;
                  }
                  .article-card:hover {
                      box-shadow: 0 4px 12px rgba(0,0,0,0.15);
                      transform: translateY(-2px);
                  }
                  .article-title {
                      font-size: 1.3rem;
                      font-weight: 600;
                      color: #0645ad;
                      margin-bottom: 0.5rem;
                      text-decoration: none;
                      display: block;
                  }
                  .article-title:hover {
                      text-decoration: underline;
                  }
                  .article-type {
                      background: #eaecf0;
                      color: #54595d;
                      padding: 0.25rem 0.75rem;
                      border-radius: 12px;
                      font-size: 0.75rem;
                      text-transform: uppercase;
                      font-weight: 500;
                      display: inline-block;
                      margin-bottom: 0.75rem;
                  }
                  .article-description {
                      color: #202122;
                      margin-bottom: 1rem;
                      font-size: 0.95rem;
                  }
                  .article-issues {
                      font-size: 0.85rem;
                      color: #d33;
                      background: #fef6e7;
                      padding: 0.75rem;
                      border-radius: 4px;
                      border-left: 3px solid #fc3;
                  }
                  .stub-indicator {
                      color: #a55858;
                      font-size: 0.8rem;
                      margin-top: 0.5rem;
                  }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>Reader Discovery Research</h1>
                  <p>Test articles for identifying content gaps and improvement opportunities</p>
              </div>

              <div class="article-grid">
                  <div class="article-card" onclick="window.location.href='ed-gallagher.html'">
                      <div class="article-type">Biography Stub</div>
                      <a href="ed-gallagher.html" class="article-title">Ed Gallagher (scientist)</a>
                      <div class="article-description">British environmental scientist and former chief executive of the Environment Agency.</div>
                      <div class="article-issues">⚠️ Missing: Early life, education details, personal life, career timeline</div>
                      <div class="stub-indicator">📝 267 words • Needs expansion</div>
                  </div>
                  
                  <div class="article-card" onclick="window.location.href='visual-technology.html'">
                      <div class="article-type">Technology Stub</div>
                      <a href="visual-technology.html" class="article-title">Visual technology</a>
                      <div class="article-description">Engineering discipline dealing with visual representation and related technologies.</div>
                      <div class="article-issues">⚠️ Missing: History, applications, technical details, industry examples</div>
                      <div class="stub-indicator">📝 90 words • Needs major expansion</div>
                  </div>
                  
                  <div class="article-card" onclick="window.location.href='richard-james.html'">
                      <div class="article-type">Biography Stub</div>
                      <a href="richard-james.html" class="article-title">Richard D. James (scientist)</a>
                      <div class="article-description">Mechanician and materials scientist, Russell J. Penrose Professor.</div>
                      <div class="article-issues">⚠️ Missing: Research details, major publications, academic contributions</div>
                      <div class="stub-indicator">📝 177 words • Needs expansion</div>
                  </div>
                  
                  <div class="article-card" onclick="window.location.href='s-vt.html'">
                      <div class="article-type">Technology Stub</div>
                      <a href="s-vt.html" class="article-title">S-VT (Sequential Valve Timing)</a>
                      <div class="article-description">Automobile variable valve timing technology developed by Mazda.</div>
                      <div class="article-issues">⚠️ Missing: Technical diagrams, implementation details, comparison with other systems</div>
                      <div class="stub-indicator">📝 89 words • Needs technical expansion</div>
                  </div>
              </div>
          </body>
          </html>
          EOF
          
          # Create Ed Gallagher article page
          cp ve-boilerplate.html ed-gallagher.html
          sed -i 's/<title>VE Boilerplate — Wikipedia‑style Visual Editor<\/title>/<title>Ed Gallagher (scientist) - Wikipedia<\/title>/' ed-gallagher.html
          sed -i 's/Sample Topic/Ed Gallagher (scientist)/' ed-gallagher.html
          
          # Replace the default articleData in ed-gallagher.html with Ed Gallagher content
          sed -i '/const articleData = {/,/};/c\
          const articleData = {\
            id: "ed-gallagher",\
            title: "Ed Gallagher (scientist)",\
            description: "British environmental scientist (born 1944)",\
            content: `'"'"'''Ed Gallagher'"'"' CBE FREng (born 4 August 1944) is a British [[scientist]]. He was a council member of [[English Nature]] and chair of the Pesticides Forum which is part of the [[Department for Environment, Food and Rural Affairs]] (DEFRA).\
          \
          == Career ==\
          Gallagher was chief executive of the [[National Rivers Authority]] from 1992 until 1995 when it was subsumed into the [[Environment Agency]] (EA) of England and Wales. He was then chief executive of the EA from 1995 to 2000.\
          \
          == Roles and honours ==\
          He was chairman of the governors at [[Middlesex University]], where he is a visiting professor. He is a [[Freeman of the City of London]] and was awarded the CBE in 2001 for environmental services.\
          \
          In February 2008, Gallagher began coordinating a group that produced a '"'"'Review of the Indirect Effects of Biofuels'"'"'.\
          \
          == References ==\
          <references />`\
          };' ed-gallagher.html
          
          # Create additional article pages with proper content
          # Visual Technology
          cp ve-boilerplate.html visual-technology.html
          sed -i 's/Sample Topic/Visual technology/g' visual-technology.html
          sed -i 's/VE Boilerplate — Wikipedia‑style Visual Editor/Visual technology - Wikipedia/' visual-technology.html
          sed -i '/const articleData = {/,/};/c\
          const articleData = {\
            id: "visual-technology",\
            title: "Visual technology",\
            description: "Engineering discipline dealing with visual representation",\
            content: `'"'"'Visual technology'"'"' is the [[engineering]] discipline dealing with visual representation.\
          \
          == Types ==\
          Visual technology includes [[photography]], [[printing]], [[augmented reality]], [[virtual reality]] and [[video]].\
          \
          == See also ==\
          * [[Audiovisual]]\
          * [[Information and communications technology]]\
          * [[Medical imaging]]\
          * [[Multimedia]]\
          * [[Visual arts]]\
          * [[Visual culture]]\
          \
          == References ==\
          <references />`\
          };' visual-technology.html
          
          # Richard James
          cp ve-boilerplate.html richard-james.html
          sed -i 's/Sample Topic/Richard D. James (scientist)/g' richard-james.html
          sed -i 's/VE Boilerplate — Wikipedia‑style Visual Editor/Richard D. James (scientist) - Wikipedia/' richard-james.html
          sed -i '/const articleData = {/,/};/c\
          const articleData = {\
            id: "richard-james",\
            title: "Richard D. James (scientist)",\
            description: "American mechanician and materials scientist",\
            content: `'"'"'Richard D. James'"'"' (born 1952) is a mechanician and materials scientist. He is currently the Russell J. Penrose Professor and Distinguished McKnight University Professor at the [[University of Minnesota]].\
          \
          == Career ==\
          James is known for his work in materials science, particularly in the field of [[shape-memory alloy]]s and [[phase transformation]]s.\
          \
          == References ==\
          <references />`\
          };' richard-james.html
          
          # S-VT
          cp ve-boilerplate.html s-vt.html
          sed -i 's/Sample Topic/S-VT (Sequential Valve Timing)/g' s-vt.html
          sed -i 's/VE Boilerplate — Wikipedia‑style Visual Editor/S-VT (Sequential Valve Timing) - Wikipedia/' s-vt.html
          sed -i '/const articleData = {/,/};/c\
          const articleData = {\
            id: "s-vt",\
            title: "S-VT (Sequential Valve Timing)",\
            description: "Automobile variable valve timing technology by Mazda",\
            content: `'"'"'S-VT'"'"', or Sequential Valve Timing, is an automobile [[variable valve timing]] technology developed by [[Mazda]].\
          \
          == Function ==\
          S-VT varies the timing of the intake valves by using oil pressure to adjust the [[camshaft]] position.\
          \
          == References ==\
          <references />`\
          };' s-vt.html

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4