name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build comparison site
        run: |
          set -euo pipefail

          # Fetch variant branches created via worktrees
          git fetch --no-tags origin alt-whisper-inline alt-whisper-modal alt-whisper-sidebar alt-floating-poll alt-section-gap || true

          mkdir -p site/variants/master site/variants/whisper-inline site/variants/whisper-modal site/variants/whisper-sidebar site/variants/floating-poll site/variants/section-gap

          # Baseline from current branch
          cp ve-boilerplate.html site/variants/master/index.html
          cp reading-styles.css site/variants/master/
          cp reading-script.js site/variants/master/

          # Whisper modal from branch
          if git rev-parse --verify --quiet origin/alt-whisper-modal >/dev/null; then
            git show origin/alt-whisper-modal:ve-boilerplate.html > site/variants/whisper-modal/index.html
            git show origin/alt-whisper-modal:reading-styles.css > site/variants/whisper-modal/reading-styles.css
            git show origin/alt-whisper-modal:reading-script.js > site/variants/whisper-modal/reading-script.js
          else
            echo "Missing branch origin/alt-whisper-modal; skipping modal variant"
          fi

          # Whisper inline from branch
          if git rev-parse --verify --quiet origin/alt-whisper-inline >/dev/null; then
            git show origin/alt-whisper-inline:ve-boilerplate.html > site/variants/whisper-inline/index.html
            git show origin/alt-whisper-inline:reading-styles.css > site/variants/whisper-inline/reading-styles.css
            git show origin/alt-whisper-inline:reading-script.js > site/variants/whisper-inline/reading-script.js
          else
            echo "Missing branch origin/alt-whisper-inline; skipping inline variant"
          fi

          # Whisper sidebar (Option 4) from branch, fallback to baseline
          if git rev-parse --verify --quiet origin/alt-whisper-sidebar >/dev/null; then
            git show origin/alt-whisper-sidebar:ve-boilerplate.html > site/variants/whisper-sidebar/index.html
            git show origin/alt-whisper-sidebar:reading-styles.css > site/variants/whisper-sidebar/reading-styles.css
            git show origin/alt-whisper-sidebar:reading-script.js > site/variants/whisper-sidebar/reading-script.js
          else
            echo "Missing branch origin/alt-whisper-sidebar; copying baseline as placeholder"
            cp site/variants/master/index.html site/variants/whisper-sidebar/index.html
            cp site/variants/master/reading-styles.css site/variants/whisper-sidebar/reading-styles.css
            cp site/variants/master/reading-script.js site/variants/whisper-sidebar/reading-script.js
          fi

          # Floating poll from branch
          if git rev-parse --verify --quiet origin/alt-floating-poll >/dev/null; then
            git show origin/alt-floating-poll:ve-boilerplate.html > site/variants/floating-poll/index.html
            git show origin/alt-floating-poll:reading-styles.css > site/variants/floating-poll/reading-styles.css
            git show origin/alt-floating-poll:reading-script.js > site/variants/floating-poll/reading-script.js
          else
            echo "Missing branch origin/alt-floating-poll; skipping floating poll variant"
          fi

          # Section gap from branch
          if git rev-parse --verify --quiet origin/alt-section-gap >/dev/null; then
            git show origin/alt-section-gap:ve-boilerplate.html > site/variants/section-gap/index.html
            git show origin/alt-section-gap:reading-styles.css > site/variants/section-gap/reading-styles.css
            git show origin/alt-section-gap:reading-script.js > site/variants/section-gap/reading-script.js
          else
            echo "Missing branch origin/alt-section-gap; skipping section gap variant"
          fi

          # Static landing page
          cp pages-index.html site/index.html

          # Cache-bust variant assets by appending build SHA to CSS/JS URLs
          for f in site/variants/master/index.html site/variants/whisper-modal/index.html site/variants/whisper-inline/index.html site/variants/floating-poll/index.html site/variants/section-gap/index.html; do
            if [ -f "$f" ]; then
              sed -i.bak -e "s|href=\"reading-styles.css\"|href=\"reading-styles.css?v=${GITHUB_SHA}\"|g" "$f" || true
              sed -i.bak -e "s|src=\"reading-script.js\"|src=\"reading-script.js?v=${GITHUB_SHA}\"|g" "$f" || true
              rm -f "$f.bak"
            fi
          done

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
